# Generated by Django 4.0.6 on 2023-03-15 18:18

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HirerInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_website', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('startup_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('project_type', models.CharField(blank=True, max_length=100, null=True)),
                ('roles_needed', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=None)),
                ('numbers_of_engineers', models.PositiveIntegerField()),
                ('tech_stacks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=None)),
                ('work_style', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TalentInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('UNAVAILABLE', 'UNAVAILABLE'), ('HIRED', 'HIRED')], default='AVAILABLE', max_length=20)),
                ('level_of_education', models.CharField(max_length=100)),
                ('years_of_experience', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(max_length=100)),
                ('github_repo_url', models.CharField(blank=True, max_length=100, null=True)),
                ('resume_url', models.CharField(blank=True, max_length=100, null=True)),
                ('hear_about_us', models.CharField(blank=True, max_length=100, null=True)),
                ('is_hired', models.BooleanField(default=False)),
                ('talent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
