# Generated by Django 4.0.6 on 2023-03-20 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_hirerinfo_user_designation_talentinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hirerinfo',
            old_name='employee_count',
            new_name='number_of_employees',
        ),
        migrations.RenameField(
            model_name='talentinfo',
            old_name='talent',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='hirerinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
