# Generated by Django 4.0.6 on 2023-03-20 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talent_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
