# Generated by Django 4.0.6 on 2023-03-21 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_talentinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='history',
            field=models.ManyToManyField(blank=True, null=True, related_name='hirer_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
