# Generated by Django 4.0.6 on 2023-03-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_hirerinfo_user_alter_user_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentinfo',
            name='level_of_education',
            field=models.CharField(max_length=120),
        ),
    ]
