# Generated by Django 4.0.6 on 2023-03-31 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_talentinfo_level_of_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentinfo',
            name='job_title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='talentinfo',
            name='years_of_experience',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
