# Generated by Django 4.0.6 on 2023-04-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_talentinfo_migration_test_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentinfo',
            name='migration_test_field',
        ),
    ]
