# Generated by Django 4.0.6 on 2023-04-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_talentinfo_migration_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='history',
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='HirerInfo',
        ),
        migrations.DeleteModel(
            name='TalentInfo',
        ),
    ]
